### ISSUE TITLE
Authorship?

### ISSUE THREAD

**Issue by NoSpamDan** [warrior1208/device_samsung_galaxys2-common#1]
Where did this repository come from?  You should be forking repos to maintain history, not uploading the work of others as your own.  While you are free to use the code, you need to retain authorship.

The original owners of this code could request that it be taken down, and nobody wants that to happen.

**Comment by warrior1208** [comment]
Okay, I'll take them down today.

**Comment by NoSpamDan** [comment]
You don't need to take them down, just use the Fork button in the upper right hand corner of Github.  That will copy the repo to your account but with authorship intact.  

Believe me, it can come in handy when hunting down commits. Of course tweaks to device config files happen as we all test things here and there.  It's the whole repo that's a concern, plus you can't then use the pull request to upload fixes or patches.  :)
